# Example 
bmc_credentials:
  bmc_ips:
    - 10.1.1.1
    - 10.1.1.2
    - 10.1.1.3
    - 10.1.1.4
    - 10.1.1.5
    - 10.1.1.6
    - 10.1.1.7

  user_name: admin
  key: ''
  encrypted_password: ''
  webhook_url: 'https://open.feishu.cn/open-apis/bot/v2/hook/xxx'